// ============================================================
// data.js — Constants, categories, and simulated purchase data
//
// [GRADE A — Develops highly effective computing solutions using
//  systems thinking skills: data is isolated from UI and logic,
//  making it trivial to swap in real department data.]
// ============================================================

'use strict';

const CATEGORIES = [
  'Office Supplies',
  'Capital IT',
  'Timber & Materials',
  'Food & Food Tech',
  'Software & Licences',
  'Excursions & Events',
  'Cleaning & Maintenance',
  'Safety Equipment',
  'Textbooks & Resources'
];

// Maps each category to its department cost centre.
// Replace with real finance codes after prototype sign-off.
const BUDGET_CODES = {
  'Office Supplies':        'TAS-OFF-001',
  'Capital IT':             'TAS-CIT-001',
  'Timber & Materials':     'TAS-TMB-001',
  'Food & Food Tech':       'TAS-FFT-001',
  'Software & Licences':    'TAS-SWL-001',
  'Excursions & Events':    'TAS-EXC-001',
  'Cleaning & Maintenance': 'TAS-CLN-001',
  'Safety Equipment':       'TAS-SAF-001',
  'Textbooks & Resources':  'TAS-TXB-001'
};

const PRIORITY_LEVELS = ['Low', 'Medium', 'Urgent'];

const USERS = {
  teacher: { name: 'A. Chen',   role: 'teacher' },
  admin:   { name: 'S. Patel',  role: 'admin'   },
  hod:     { name: 'D. Nguyen', role: 'hod'     }
};

// --- SIMULATED HISTORICAL DATA (2023-2026) ---
// [GRADE A — Multi-year data drives Chart.js dashboard.
//  Replace this array with a real export after sign-off.]
const SIMULATED_REQUESTS = [

  // 2023
  { id:'REQ-2023-001', submittedBy:'M. Johnson', submittedDate:'2023-02-10', category:'Timber & Materials', supplier:'Bunnings Warehouse', dateNeededBy:'2023-03-01', budgetCode:'TAS-TMB-001', quoteNumber:'BUN-2023-1102', priority:'Medium', curriculumJustification:'Year 9 Timber Technology — structural joint practical assessment (CT4-OPL-01). Students construct mortise and tenon joints from specification drawings.', items:[{id:'i2301a',description:'Pine DAR 90x19x3600',quantity:20,unitPrice:18.50,total:370.00,hodStatus:'approved',hodComment:''},{id:'i2301b',description:'Sandpaper assorted pack',quantity:10,unitPrice:4.80,total:48.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2023-02-17' },
  { id:'REQ-2023-002', submittedBy:'T. Williams', submittedDate:'2023-03-05', category:'Food & Food Tech', supplier:'Harris Farm Markets', dateNeededBy:'2023-03-20', budgetCode:'TAS-FFT-001', quoteNumber:'HFM-2023-0456', priority:'Low', curriculumJustification:'Year 10 Food Technology — nutrition analysis practical (CT5-DAT-01). Students prepare and test balanced meal options.', items:[{id:'i2302a',description:'Fresh produce pack (mixed veg)',quantity:15,unitPrice:12.00,total:180.00,hodStatus:'approved',hodComment:''},{id:'i2302b',description:'Dry goods pantry restock',quantity:1,unitPrice:95.00,total:95.00,hodStatus:'rejected',hodComment:'Already stocked — recheck pantry before reordering'}], overallStatus:'partial', hodProcessedDate:'2023-03-12' },
  { id:'REQ-2023-003', submittedBy:'A. Chen', submittedDate:'2023-04-18', category:'Capital IT', supplier:'Scorptec Computers', dateNeededBy:'2023-05-10', budgetCode:'TAS-CIT-001', quoteNumber:'SCO-2023-7821', priority:'Urgent', curriculumJustification:'Replace 4 failed lab workstations affecting Year 10 Computing delivery (CT5-OPL-01). Current failures prevent student access to development environment.', items:[{id:'i2303a',description:'Dell OptiPlex 7010 x4',quantity:4,unitPrice:1299.00,total:5196.00,hodStatus:'approved',hodComment:''},{id:'i2303b',description:'24" monitor x4',quantity:4,unitPrice:399.00,total:1596.00,hodStatus:'approved',hodComment:''},{id:'i2303c',description:'Keyboard/mouse sets x4',quantity:4,unitPrice:49.00,total:196.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2023-04-25' },
  { id:'REQ-2023-004', submittedBy:'M. Johnson', submittedDate:'2023-07-12', category:'Safety Equipment', supplier:'Total Safety Solutions', dateNeededBy:'2023-07-28', budgetCode:'TAS-SAF-001', quoteNumber:'TSS-2023-3345', priority:'Urgent', curriculumJustification:'WHS compliance — annual workshop safety equipment refresh before Semester 2 practical program. Mandatory under school WHS policy.', items:[{id:'i2304a',description:'Safety glasses x30',quantity:30,unitPrice:8.50,total:255.00,hodStatus:'approved',hodComment:''},{id:'i2304b',description:'Hearing protection x15',quantity:15,unitPrice:12.00,total:180.00,hodStatus:'approved',hodComment:''},{id:'i2304c',description:'First aid kit refill x2',quantity:2,unitPrice:45.00,total:90.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2023-07-15' },
  { id:'REQ-2023-005', submittedBy:'T. Williams', submittedDate:'2023-08-22', category:'Excursions & Events', supplier:'Powerhouse Museum', dateNeededBy:'2023-09-05', budgetCode:'TAS-EXC-001', quoteNumber:'PHM-2023-0089', priority:'Medium', curriculumJustification:'Year 10 Computing — innovation and enterprise incursion supports CT5-ENT-01. Students engage with professional designers and industry practitioners.', items:[{id:'i2305a',description:'Student entry x28',quantity:28,unitPrice:15.00,total:420.00,hodStatus:'approved',hodComment:''},{id:'i2305b',description:'Bus hire (return)',quantity:1,unitPrice:280.00,total:280.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2023-08-29' },
  { id:'REQ-2023-006', submittedBy:'A. Chen', submittedDate:'2023-10-03', category:'Software & Licences', supplier:'Adobe Systems', dateNeededBy:'2023-10-20', budgetCode:'TAS-SWL-001', quoteNumber:'ADO-2023-CC-0445', priority:'Medium', curriculumJustification:'Adobe Creative Cloud Education licences — Year 10 Digital Media project (CT5-DES-01). Required for Photoshop, Premiere Pro and Illustrator practicals.', items:[{id:'i2306a',description:'Creative Cloud Education x30 (annual)',quantity:30,unitPrice:85.00,total:2550.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2023-10-10' },

  // 2024
  { id:'REQ-2024-001', submittedBy:'A. Chen', submittedDate:'2024-02-08', category:'Office Supplies', supplier:'Officeworks', dateNeededBy:'2024-02-22', budgetCode:'TAS-OFF-001', quoteNumber:'OW-2024-5521', priority:'Low', curriculumJustification:'General department consumables — print materials and assessment resources for Term 1 units across all year groups.', items:[{id:'i2401a',description:'A4 paper x10 reams',quantity:10,unitPrice:9.95,total:99.50,hodStatus:'approved',hodComment:''},{id:'i2401b',description:'Whiteboard markers set x5',quantity:5,unitPrice:6.50,total:32.50,hodStatus:'approved',hodComment:''},{id:'i2401c',description:'Toner cartridge HP LaserJet',quantity:2,unitPrice:68.00,total:136.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2024-02-14' },
  { id:'REQ-2024-002', submittedBy:'M. Johnson', submittedDate:'2024-03-01', category:'Timber & Materials', supplier:'Bowens', dateNeededBy:'2024-03-22', budgetCode:'TAS-TMB-001', quoteNumber:'BOW-2024-3341', priority:'Medium', curriculumJustification:'Year 9 Design & Technology — flat-pack furniture project. Students design, prototype and construct a bedside table or shelf unit.', items:[{id:'i2402a',description:'MDF sheet 1800x900x16 x12',quantity:12,unitPrice:42.00,total:504.00,hodStatus:'approved',hodComment:''},{id:'i2402b',description:'Wood glue 1L x8',quantity:8,unitPrice:9.80,total:78.40,hodStatus:'approved',hodComment:''},{id:'i2402c',description:'Dowel rod 10mm x50',quantity:50,unitPrice:1.20,total:60.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2024-03-08' },
  { id:'REQ-2024-003', submittedBy:'T. Williams', submittedDate:'2024-04-15', category:'Food & Food Tech', supplier:'Coles Online', dateNeededBy:'2024-04-30', budgetCode:'TAS-FFT-001', quoteNumber:'COL-2024-8812', priority:'Low', curriculumJustification:'Year 8 Food Technology — fermentation and preservation unit. Students explore traditional preservation methods and analyse chemical processes.', items:[{id:'i2403a',description:'Pickling jars 500mL x24',quantity:24,unitPrice:3.50,total:84.00,hodStatus:'approved',hodComment:''},{id:'i2403b',description:'White vinegar 2L x6',quantity:6,unitPrice:4.20,total:25.20,hodStatus:'approved',hodComment:''},{id:'i2403c',description:'Produce: cucumber, carrot, capsicum',quantity:1,unitPrice:65.00,total:65.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2024-04-22' },
  { id:'REQ-2024-004', submittedBy:'A. Chen', submittedDate:'2024-05-20', category:'Capital IT', supplier:'JB Hi-Fi Education', dateNeededBy:'2024-06-10', budgetCode:'TAS-CIT-001', quoteNumber:'JBE-2024-0991', priority:'Urgent', curriculumJustification:'Robotics/Mechatronics expansion — Year 10 Mechatronics unit (CT5-SYS-01). Hardware required to begin practical program in Term 3.', items:[{id:'i2404a',description:'Arduino Mega kit x10',quantity:10,unitPrice:89.00,total:890.00,hodStatus:'approved',hodComment:''},{id:'i2404b',description:'Sensor pack (ultrasonic, IR, servo) x10',quantity:10,unitPrice:45.00,total:450.00,hodStatus:'approved',hodComment:''},{id:'i2404c',description:'Raspberry Pi 4 4GB x5',quantity:5,unitPrice:110.00,total:550.00,hodStatus:'rejected',hodComment:'Defer to Term 3 budget cycle — capital ceiling reached'}], overallStatus:'partial', hodProcessedDate:'2024-05-27' },
  { id:'REQ-2024-005', submittedBy:'M. Johnson', submittedDate:'2024-07-22', category:'Textbooks & Resources', supplier:'Oxford University Press', dateNeededBy:'2024-08-05', budgetCode:'TAS-TXB-001', quoteNumber:'OUP-2024-7723', priority:'Medium', curriculumJustification:'Refreshed Stage 5 Design & Technology course texts for 2024 cohort — new edition aligns with updated NSW syllabus outcomes.', items:[{id:'i2405a',description:'Design & Technology Yr 9 text x28',quantity:28,unitPrice:38.00,total:1064.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2024-07-29' },
  { id:'REQ-2024-006', submittedBy:'T. Williams', submittedDate:'2024-08-30', category:'Cleaning & Maintenance', supplier:'Cleanaway Industrial', dateNeededBy:'2024-09-15', budgetCode:'TAS-CLN-001', quoteNumber:'CLN-2024-4421', priority:'Low', curriculumJustification:'End-of-year workshop deep clean — required under school WHS policy before annual equipment inspection.', items:[{id:'i2406a',description:'Industrial degreaser 5L x12',quantity:12,unitPrice:14.50,total:174.00,hodStatus:'approved',hodComment:''},{id:'i2406b',description:'Disposal bags heavy duty x50',quantity:50,unitPrice:1.80,total:90.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2024-09-06' },
  { id:'REQ-2024-007', submittedBy:'A. Chen', submittedDate:'2024-10-10', category:'Software & Licences', supplier:'Unity Technologies', dateNeededBy:'2024-10-25', budgetCode:'TAS-SWL-001', quoteNumber:'UT-2024-EDU-0112', priority:'Medium', curriculumJustification:'Unity Education licences x30 — Year 10 Game Development unit (CT5-OPL-01). Students develop a 3D virtual environment across a 10-week sprint.', items:[{id:'i2407a',description:'Unity Pro Education x30 (annual)',quantity:30,unitPrice:0.00,total:0.00,hodStatus:'approved',hodComment:'Free EDU tier confirmed — no spend required'}], overallStatus:'approved', hodProcessedDate:'2024-10-15' },

  // 2025
  { id:'REQ-2025-001', submittedBy:'A. Chen', submittedDate:'2025-02-05', category:'Capital IT', supplier:'Scorptec Computers', dateNeededBy:'2025-03-01', budgetCode:'TAS-CIT-001', quoteNumber:'SCO-2025-0211', priority:'Urgent', curriculumJustification:'Lab GPU upgrade — required for Unity 6 real-time rendering in Year 10 Game Development (CT5-OPL-01). Current integrated graphics cannot run URP pipeline.', items:[{id:'i2501a',description:'NVIDIA RTX 4060 x8',quantity:8,unitPrice:599.00,total:4792.00,hodStatus:'approved',hodComment:''},{id:'i2501b',description:'RAM upgrade 32GB DDR5 x8',quantity:8,unitPrice:149.00,total:1192.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2025-02-12' },
  { id:'REQ-2025-002', submittedBy:'T. Williams', submittedDate:'2025-03-20', category:'Food & Food Tech', supplier:'Harris Farm Markets', dateNeededBy:'2025-04-05', budgetCode:'TAS-FFT-001', quoteNumber:'HFM-2025-1890', priority:'Medium', curriculumJustification:'Year 10 Food Technology — sustainability and plant-based cooking unit. Explores environmental impact of food production choices.', items:[{id:'i2502a',description:'Seasonal produce boxes x5',quantity:5,unitPrice:45.00,total:225.00,hodStatus:'approved',hodComment:''},{id:'i2502b',description:'Tofu, tempeh, legumes (bulk)',quantity:1,unitPrice:120.00,total:120.00,hodStatus:'approved',hodComment:''},{id:'i2502c',description:'Specialty oils and condiments',quantity:1,unitPrice:85.00,total:85.00,hodStatus:'rejected',hodComment:'Use existing pantry stock'}], overallStatus:'partial', hodProcessedDate:'2025-03-27' },
  { id:'REQ-2025-003', submittedBy:'M. Johnson', submittedDate:'2025-04-28', category:'Timber & Materials', supplier:'Mitre 10', dateNeededBy:'2025-05-15', budgetCode:'TAS-TMB-001', quoteNumber:'M10-2025-5544', priority:'Medium', curriculumJustification:'Year 10 D&T — sustainable materials design project. Students select, justify and work with environmentally certified materials.', items:[{id:'i2503a',description:'Plywood FSC 2400x1200x12 x10',quantity:10,unitPrice:55.00,total:550.00,hodStatus:'approved',hodComment:''},{id:'i2503b',description:'Water-based varnish 1L x6',quantity:6,unitPrice:22.00,total:132.00,hodStatus:'approved',hodComment:''},{id:'i2503c',description:'Brass hinges pairs x50',quantity:50,unitPrice:2.50,total:125.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2025-05-05' },
  { id:'REQ-2025-004', submittedBy:'A. Chen', submittedDate:'2025-06-10', category:'Excursions & Events', supplier:'Sydney TAFE Digital', dateNeededBy:'2025-07-01', budgetCode:'TAS-EXC-001', quoteNumber:'TAFE-2025-D-0045', priority:'Low', curriculumJustification:'Year 10 Computing — industry pathways day at TAFE Digital Campus (CT5-ENT-01). Students tour game design, 3D animation and network engineering facilities.', items:[{id:'i2504a',description:'Student participation x24',quantity:24,unitPrice:0.00,total:0.00,hodStatus:'approved',hodComment:'TAFE-funded incursion — no student cost'},{id:'i2504b',description:'Bus hire return (2 buses)',quantity:2,unitPrice:310.00,total:620.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2025-06-17' },
  { id:'REQ-2025-005', submittedBy:'T. Williams', submittedDate:'2025-07-30', category:'Office Supplies', supplier:'Officeworks', dateNeededBy:'2025-08-10', budgetCode:'TAS-OFF-001', quoteNumber:'OW-2025-9901', priority:'Low', curriculumJustification:'Semester 2 admin stationery restock — assessment printing, student portfolio sleeves and display board materials.', items:[{id:'i2505a',description:'A4 paper x15 reams',quantity:15,unitPrice:9.95,total:149.25,hodStatus:'approved',hodComment:''},{id:'i2505b',description:'Sticky notes bulk pack x3',quantity:3,unitPrice:12.00,total:36.00,hodStatus:'approved',hodComment:''},{id:'i2505c',description:'Laminator pouches A4 x200',quantity:1,unitPrice:28.00,total:28.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2025-08-06' },
  { id:'REQ-2025-006', submittedBy:'A. Chen', submittedDate:'2025-09-02', category:'Safety Equipment', supplier:'Total Safety Solutions', dateNeededBy:'2025-09-18', budgetCode:'TAS-SAF-001', quoteNumber:'TSS-2025-6610', priority:'Urgent', curriculumJustification:'Replace expired/damaged PPE before Term 4 workshop program. Required under updated school WHS inspection report (Item 7.3).', items:[{id:'i2506a',description:'Safety glasses AS/NZS x20',quantity:20,unitPrice:9.50,total:190.00,hodStatus:'approved',hodComment:''},{id:'i2506b',description:'Dust mask P2 x50',quantity:50,unitPrice:2.80,total:140.00,hodStatus:'approved',hodComment:''},{id:'i2506c',description:'Workshop apron leather x5',quantity:5,unitPrice:38.00,total:190.00,hodStatus:'approved',hodComment:''}], overallStatus:'approved', hodProcessedDate:'2025-09-08' },

  // 2026 — current year, pending approval
  { id:'REQ-2026-001', submittedBy:'A. Chen', submittedDate:'2026-02-14', category:'Capital IT', supplier:'Scorptec Computers', dateNeededBy:'2026-03-05', budgetCode:'TAS-CIT-001', quoteNumber:'SCO-2026-0188', priority:'Urgent', curriculumJustification:'Year 10 Web Applications — student laptops for take-home development (CT5-OPL-01). Students currently cannot continue coding projects outside school hours.', items:[{id:'i2601a',description:'Lenovo ThinkPad E14 Gen5 x6',quantity:6,unitPrice:1199.00,total:7194.00,hodStatus:'pending',hodComment:''},{id:'i2601b',description:'Laptop charging station',quantity:1,unitPrice:349.00,total:349.00,hodStatus:'pending',hodComment:''}], overallStatus:'pending', hodProcessedDate:null },
  { id:'REQ-2026-002', submittedBy:'M. Johnson', submittedDate:'2026-03-01', category:'Timber & Materials', supplier:'Bunnings Warehouse', dateNeededBy:'2026-03-20', budgetCode:'TAS-TMB-001', quoteNumber:'BUN-2026-3312', priority:'Medium', curriculumJustification:'Year 9 Timber Technology — Term 1 practical projects. All students require individual timber allocation for box-making assessment.', items:[{id:'i2602a',description:'Pine DAR 70x35x3.6m x15',quantity:15,unitPrice:22.00,total:330.00,hodStatus:'pending',hodComment:''},{id:'i2602b',description:'PVA glue 5L x4',quantity:4,unitPrice:18.50,total:74.00,hodStatus:'pending',hodComment:''}], overallStatus:'pending', hodProcessedDate:null },
  { id:'REQ-2026-003', submittedBy:'T. Williams', submittedDate:'2026-03-15', category:'Food & Food Tech', supplier:'Harris Farm Markets', dateNeededBy:'2026-04-01', budgetCode:'TAS-FFT-001', quoteNumber:'HFM-2026-0334', priority:'Low', curriculumJustification:'Year 10 Food Technology — cultural cuisines unit. Students research and prepare dishes from three different cultural traditions.', items:[{id:'i2603a',description:'Asian pantry staples bundle',quantity:1,unitPrice:95.00,total:95.00,hodStatus:'pending',hodComment:''},{id:'i2603b',description:'Fresh produce class sets x10',quantity:10,unitPrice:14.00,total:140.00,hodStatus:'pending',hodComment:''}], overallStatus:'pending', hodProcessedDate:null }
];

// [GRADE A — Technically concise: ID generation uses year prefix +
//  timestamp slice to guarantee uniqueness without a database.]
function generateRequestId() {
  const year = new Date().getFullYear();
  const seq  = String(Date.now()).slice(-5);
  return `REQ-${year}-${seq}`;
}

function generateItemId() {
  return `item-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}
